baseURL = 'https://darefitz.github.io/'
languageCode = 'en-us'
title = 'Darren Fitzpatrick'
theme = "paper"

[params]
  # color style
  color = 'wheat'                           # linen, wheat, gray, light

  # header social icons
  github = 'darefitz'                 # github.com/YOUR_GITHUB_ID




